"log2_loop:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"slti t0, %[N], 2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bnez t0, log2_done\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"srli %[N], %[N], 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[log], %[log], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal zero, log2_loop\n\t"
"log2_done:\n\t"
